name: Update README

on:
  schedule:
    - cron: '0 * * * *' # Update every hour

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run update-readme.js
      run: node update-readme.js

    - name: Commit and push if changed
      run: |
        git config user.name 'GitHub Actions'
        git config user.email 'actions@github.com'
        git add README.md
        git diff --staged --quiet || git commit -m 'Update status in README.md'
        git push